### ISSUE TITLE
Empty output when skimming with v2

### ISSUE THREAD

**Issue by holgerbrandl** [ropensci/skimr#450]
Example
```
λ R

R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> require(skimr)
Loading required package: skimr
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252
[2] LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] skimr_2.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1       digest_0.6.18    crayon_1.3.4     dplyr_0.8.0.1
 [5] assertthat_0.2.1 repr_1.0.0       R6_2.4.0         jsonlite_1.6
 [9] magrittr_1.5     pillar_1.3.1     rlang_0.3.1      tools_3.5.2
[13] glue_1.3.1       purrr_0.3.2      xfun_0.4         compiler_3.5.2
[17] base64enc_0.1-3  pkgconfig_2.0.2  htmltools_0.3.6  knitr_1.22
[21] tidyselect_0.2.5 tibble_2.0.1
> skim(iris)
-- Data Summary ------------------------
                        Value
Name                     iris
Number of rows            150
Number of columns           5

Column type frequency:
  factor                    1
  numeric                   4

Group variables          None

-- Variable type: factor -------------------------------------------------------


-- Variable type: numeric ------------------------------------------------------

>
```

It picks up that there is one factor and 4 numeric attributes but fails to show summaries.

**Comment by holgerbrandl** [comment]
Doing the same with skimr_1.0.6 it gives a more complete output:
```
-- Variable type:numeric -------------------------------------------------------
     variable missing complete   n mean   sd  p0 p25  p50 p75 p100     hist
 Petal.Length       0      150 150 3.76 1.77 1   1.6 4.35 5.1  6.9 <U+2587><U+2581><U+2581><U+2582><U+2585><U+2585><U+2583><U+2581>
  Petal.Width       0      150 150 1.2  0.76 0.1 0.3 1.3  1.8  2.5 <U+2587><U+2581><U+2581><U+2585><U+2583><U+2583><U+2582><U+2582>
 Sepal.Length       0      150 150 5.84 0.83 4.3 5.1 5.8  6.4  7.9 <U+2582><U+2587><U+2585><U+2587><U+2586><U+2585><U+2582><U+2582>
  Sepal.Width       0      150 150 3.06 0.44 2   2.8 3    3.3  4.4 <U+2581><U+2582><U+2585><U+2587><U+2583><U+2582><U+2581><U+2581>
```
which seems fine except for the incorrectly rendered unicode characters.

**Comment by michaelquinn32** [comment]
Thanks for reporting. I'll be taking a look at it soon enough, but need to get some other stuff cleared out first.

**Comment by elinw** [comment]
Okay that is not happening when we run the tests. I bet it is some combination of dplyr and rlang versions.

**Comment by elinw** [comment]
I just merged a PR for the V2 branch.  Would you mind trying it again?   Also if you are in RStudio would you mind doing

```
result <- skimr(iris)
View(result)

```
And see if the data is there in the data frame? That will help isolate the issue.

**Comment by holgerbrandl** [comment]
I have installed the latest branch. It is showing data with View but printing the result is still not working for me: 
![image](https://user-images.githubusercontent.com/200952/57307915-aafc6480-70e5-11e9-8f5d-c52b5d93e622.png)

Session info is
´´´
> sessionInfo()                                                                                  
R version 3.5.2 (2018-12-20)                                                                     
Platform: x86_64-w64-mingw32/x64 (64-bit)                                                        
Running under: Windows 10 x64 (build 16299)                                                      
                                                                                                 
Matrix products: default                                                                         
                                                                                                 
locale:                                                                                          
[1] LC_COLLATE=English_United States.1252                                                        
[2] LC_CTYPE=English_United States.1252                                                          
[3] LC_MONETARY=English_United States.1252                                                       
[4] LC_NUMERIC=C                                                                                 
[5] LC_TIME=English_United States.1252                                                           
                                                                                                 
attached base packages:                                                                          
[1] stats     graphics  grDevices utils     datasets  methods   base                             
                                                                                                 
other attached packages:                                                                         
[1] skimr_2.0                                                                                    
                                                                                                 
loaded via a namespace (and not attached):                                                       
 [1] Rcpp_1.0.1        pillar_1.3.1      compiler_3.5.2    prettyunits_1.0.2                     
 [5] base64enc_0.1-3   remotes_2.0.2     tools_3.5.2       digest_0.6.18                         
 [9] pkgbuild_1.0.2    pkgload_1.0.2     jsonlite_1.6      memoise_1.1.0                         
[13] tibble_2.1.1      pkgconfig_2.0.2   rlang_0.3.4       cli_1.1.0                             
[17] curl_3.3          xfun_0.6          stringr_1.4.0     repr_1.0.0                            
[21] withr_2.1.2       dplyr_0.8.0.1     knitr_1.22        desc_1.2.0                            
[25] fs_1.2.6          devtools_2.0.1    rprojroot_1.3-2   tidyselect_0.2.5                      
[29] glue_1.3.1        R6_2.4.0          processx_3.2.1    fansi_0.4.0                           
[33] sessioninfo_1.1.1 tidyr_0.8.3       callr_3.1.1       purrr_0.3.2                           
[37] magrittr_1.5      backports_1.1.3   ps_1.3.0          htmltools_0.3.6                       
[41] usethis_1.4.0     assertthat_0.2.1  utf8_1.1.4        stringi_1.4.3                         
[45] crayon_1.3.4                                                                                
>                                                                                                
´´´

**Comment by elinw** [comment]
Okay thanks, so it's a problem with the print method that's helpful ... though mysterious.

**Comment by elinw** [comment]
I just tried this on a windows machine and didn't have the problem, so it's something different.  Can you try mtcars and chickwts and see if the same thing happens?

**Comment by holgerbrandl** [comment]
I've managed to narrow it down a bit. When using command prompt (CMD) it outputs 

```
> skim(iris)
-- Data Summary ------------------------
                        Value
Name                     iris
Number of rows            150
Number of columns           5

Column type frequency:
  factor                    1
  numeric                   4

Group variables          None

-- Variable type: factor -------------------------------------------------------
  skim_variable missing complete     n ordered n_unique
1 Species             0      150   150 FALSE          3
  top_counts
1 set: 50, ver: 50, vir: 50

-- Variable type: numeric ------------------------------------------------------
  skim_variable missing complete     n  mean    sd    p0   p25   p50   p75  p100
1 Sepal.Length        0      150   150  5.84 0.828   4.3   5.1  5.8    6.4   7.9
2 Sepal.Width         0      150   150  3.06 0.436   2     2.8  3      3.3   4.4
3 Petal.Length        0      150   150  3.76 1.77    1     1.6  4.35   5.1   6.9
4 Petal.Width         0      150   150  1.20 0.762   0.1   0.3  1.3    1.8   2.5
  hist
1 <U+2586><U+2587><U+2587><U+2585><U+2582>
2 <U+2581><U+2586><U+2587><U+2582><U+2581>
3 <U+2587><U+2581><U+2586><U+2587><U+2582>
4 <U+2587><U+2581><U+2587><U+2585><U+2583>
```
So except for the incorrectly rendered histogram it seems fine.

However, when using https://cmder.net/ with git-bash I'm observing the behaviour described above.

**Comment by elinw** [comment]
Oh you didn't mention that context before.
Because you are on Windows (as explained elsewhere) the histograms in the data frame will not work. You can, however, use the  `inline_hist()` function on its own (with apply) to get the histograms as a character vector.

**Comment by elinw** [comment]
Wait you are in git bash?  Can you try another bash?

**Comment by elinw** [comment]
@michaelquinn32 @holgerbrandl  It seems like this issue might be related to gitbash or to the cmder.net environment.

**Comment by petrbouchal** [comment]
FWIW on a mac this issue happens in RStudio (both console and Rmarkdown notebook) but not in plain iTerm console.

**Comment by michaelquinn32** [comment]
I'm wondering if the root cause of this is ASCII handling across environments.  Could you install from the develop branch? 

```
devtools::install_github("ropensci/skimr", ref = "develop")
```

And try the following?

```
library(skimr)
skimmed <- skim(iris)
print(skimmed, strip_metadata = FALSE)
```

Thanks!

**Comment by petrbouchal** [comment]
Thanks! Yes now it looks as it should (and the strip_metadata parameter makes the difference).

**Comment by michaelquinn32** [comment]
Can you include the output here?

**Comment by petrbouchal** [comment]
```
── Data Summary ────────────────────────
                           Values
Name                       iris  
Number of rows             150   
Number of columns          5     
_______________________          
Column type frequency:           
  factor                   1     
  numeric                  4     
________________________         
Group variables            None  

── Variable type: factor ─────────────────────────────────────────────────────────────────────────────────
# A tibble: 1 x 6
  skim_variable n_missing complete_rate ordered n_unique top_counts               
* <chr>             <int>         <dbl> <lgl>      <int> <chr>                    
1 Species               0             1 FALSE          3 set: 50, ver: 50, vir: 50

── Variable type: numeric ────────────────────────────────────────────────────────────────────────────────
# A tibble: 4 x 11
  skim_variable n_missing complete_rate  mean    sd    p0   p25   p50   p75  p100 hist 
* <chr>             <int>         <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <chr>
1 Sepal.Length          0             1  5.84 0.828   4.3   5.1  5.8    6.4   7.9 ▆▇▇▅▂
2 Sepal.Width           0             1  3.06 0.436   2     2.8  3      3.3   4.4 ▁▆▇▂▁
3 Petal.Length          0             1  3.76 1.77    1     1.6  4.35   5.1   6.9 ▇▁▆▇▂
4 Petal.Width           0             1  1.20 0.762   0.1   0.3  1.3    1.8   2.5 ▇▁▇▅▃
```

**Comment by elinw** [comment]
Great, I'm going to close this since the PR solves the issue . #518  @michaelquinn32  reopen if you think it needs to be.

**Comment by elinw** [comment]
I'm wondering if this was also the crayon issue #554

**Comment by petrbouchal** [comment]
Probably: after updating crayon to the [current github version](https://github.com/r-lib/crayon/commit/84be62074ad5b3ede54dd035ef4003f808f34f12) skimr prints the stats correctly without the need for any further parameters or options.
